channels:
  - conda-forge
  - bioconda
dependencies:
- python=3.10
- pip 
- pandas 
- pytest 
- jupyter
- notebook
- pyogrio
- openpyxl
- black=22.3.0 
- psycopg2
- python-dotenv
- prospector[with_everything]=1.7.7
- pytest-dotenv
- sqlalchemy
- dask[dataframe]
- python-kaleido=0.2.1
- snakemake-minimal
- scikit-learn=1.3.2