import os
import traceback
import json
from zoomin import disaggregation_manager as disagg_manager
from zoomin import snakemake_utils as sm_utls
from zoomin.post_disagg_calculation import perform_post_disagg_calculation
from dotenv import load_dotenv, find_dotenv

# find .env automagically by walking up directories until it's found
dotenv_path = find_dotenv()
# load up the entries as environment variables
load_dotenv(dotenv_path)

db_name = os.environ.get("DB_NAME")

eucalc_years = ["2020", "2025", "2030", "2035", "2040", "2045", "2050"]

bad_proxy_dict = {}

def log_error(error, file_name):
    FILE_PATH = f"output_logs/{db_name}/error_{file_name}.log"

    with open(FILE_PATH, 'w') as f:
        print(error)
        f.write(error)

rule all:
    input:
        "bad_proxy_log.json"

pathways = ["national", "with_behavioural_changes"]
eucalc_vars_to_disagg = sm_utls.get_eucalc_vars("disagg")
eucalc_vars_post_disagg_calc = sm_utls.get_eucalc_vars("post_disagg_calc")

# Define a wildcard for each parameter
wildcard_constraints:
    # eucalc vars 
    wc_pathway = "|".join(pathways),

    wc_eucalc_var_to_disagg = "|".join(eucalc_vars_to_disagg),
    wc_eucalc_var_post_disagg_calc = "|".join(eucalc_vars_post_disagg_calc), 

    wc_eucalc_year = "|".join(eucalc_years),

    wc_db_name = db_name

# =============================================================
#####################      EUCALC VARS     ####################
# =============================================================

# DISAGGREGATION
rule disaggregate_eucalc_vars:
    output:
        touch("output_logs/{wc_db_name}/{wc_eucalc_var_to_disagg}_{wc_eucalc_year}_{wc_pathway}.log")
    run:
        try:
            bad_proxy = disagg_manager.process_eucalc_var(wildcards.wc_eucalc_var_to_disagg, 
                                                wildcards.wc_pathway,
                                                wildcards.wc_eucalc_year)

            if bad_proxy is not None:
                bad_proxy_dict.update({f"{wildcards.wc_eucalc_var_to_disagg}_{wildcards.wc_eucalc_year}_{wildcards.wc_pathway}": bad_proxy})

        except Exception as e:
            sm_utls.clear_rows_from_processed_data(wildcards.wc_eucalc_var_to_disagg, wc_eucalc_year, wc_pathway)
            print('DELETED var')
            log_error(traceback.format_exc(), f"{wildcards.wc_eucalc_var_to_disagg}_{wildcards.wc_eucalc_year}_{wildcards.wc_pathway}")
            raise e
            
rule end_of_disaggregation:
    input:
        expand("output_logs/{db_name}/{var_name}_{year}_{pathway}.log", 
                db_name=db_name,
                var_name=eucalc_vars_to_disagg,
                year=eucalc_years,
                pathway=pathways)
    output:
        touch("output_logs/{wc_db_name}/finished_disaggregation.log")


# POST DISAGGREGATION CALCULATION 

rule calculate_eucalc_vars_post_disaggregation:
    input:
        f"output_logs/{db_name}/finished_disaggregation.log"
    output:
        touch("output_logs/{wc_db_name}/{wc_eucalc_var_post_disagg_calc}.log")
    run:
        try:
            perform_post_disagg_calculation(wildcards.wc_eucalc_var_post_disagg_calc)

        except Exception as e:
            sm_utls.clear_rows_from_processed_data(wildcards.wc_eucalc_var_post_disagg_calc)
            log_error(traceback.format_exc(), wildcards.wc_eucalc_var_post_disagg_calc)
            raise e

#================================================================================================

rule final:
    input:
        expand("output_logs/{db_name}/{var_name}.log", 
                     db_name=db_name,
                    var_name=eucalc_vars_post_disagg_calc)
    output:
        "bad_proxy_log.json"
    run:
        # log bad proxies 
        with open("bad_proxy_log.json", 'w') as fp:
            json.dump(bad_proxy_dict, fp)

