name: Python Package using Conda

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.*
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y python=3.11
        conda env update --file requirements.yml --name base
        pip install -e.
    - name: Check black formatting
      run: |
        black --check zoomin
        black --check tests
